# all float on
windowrule {
    name = master_float
    match:class = .*

    float = on
}

# Default float size (excludes apps that should pick their own size)
windowrule {
    name = master_float_size
    match:class = negative:^([Ww]aydroid.*|jetbrains-.*|winboat-Microsoft Edge|winboat|osu!|org\.kde\.dolphin|osu!\.exe|anydesk|org\.kde\.kate|jetbrains-studio|dolphin)$
    match:title = negative:^()$

    size = 1200 800
}
