# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5
# exec-once = ~/.config/hypr/autofloat.sh


# all float on (disabled at boot, toggle with Super + F11)
exec-once = hyprctl --batch "keyword 'windowrule[master_float]:enable false' ; keyword 'windowrule[master_float_size]:enable false'"
