input {
    kb_layout = br,us
    kb_options =
    accel_profile = flat
    sensitivity = 0.0
    # force_no_accel = true
}

ecosystem {
    no_update_news = true
    no_donation_nag = true
}

xwayland {
    force_zero_scaling = true
    create_abstract_socket = false
}

misc {
    focus_on_activate = false
    middle_click_paste = false
    animate_mouse_windowdragging = true
    vrr = 1
}

general {
    allow_tearing = false
}

render {
    direct_scanout = 1
}

source = ~/.config/hypr/custom/animations/active/active.conf

source = ~/.config/hypr/custom/autofloat_rules.conf
