input {
    kb_layout = br,us
    kb_options = grp:win_space_toggle
}

device {
    name = logitech-g-pro--1
    accel_profile = flat
    sensitivity = 0.0
}

misc {
    vfr = false
    vrr = 0
    focus_on_activate = false
    middle_click_paste = false
}

general {
    allow_tearing = false
}
