input {
    kb_layout = br,us
    kb_options = grp:win_space_toggle
    accel_profile = flat
    sensitivity = 0.0
    # force_no_accel = true
}

cursor {
    no_hardware_cursors = true
    no_break_fs_vrr = 1
    default_monitor = DP-1
    use_cpu_buffer = 0
}

ecosystem {
    no_update_news = true
    no_donation_nag = true
}

xwayland {
    force_zero_scaling = true
    create_abstract_socket = false
}

misc {
    font_family = Inter Variable
    vfr = true
    vrr = 2
    focus_on_activate = false
    middle_click_paste = false
    animate_mouse_windowdragging = true
}

general {
    allow_tearing = false
}

# Dusky Animations
source = ~/.config/hypr/custom/animations/active/active.conf

# Dusky Plugins (HyprExpo)
#
# `hyprpm update && hyprpm add https://github.com/hyprwm/hyprland-plugins && hyprpm enable hyprexpo`
#
# plugin {
#     hyprexpo {
#         columns = 3
#         gap_size = 5
#         bg_col = rgb(111111)
#         workspace_method = first 1 # [center/first] [workspace] e.g. first 1 or center m+1
#         gesture_distance = 300 # how far is the "max" for the gesture
#     }
# }
