# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrulev2 = opacity 0.89 override 0.89 override, class:.*

# Disable blur for all xwayland apps
# windowrulev2 = noblur, xwayland:1

# --- osu! specific rules ---
# Allows tearing, disables rounding, blur, shadows, and animations just for the game
# This ensures perfect 144Hz Direct Scanout without touching the global desktop settings!
windowrule = match:class ^(osu\!)$, immediate on
windowrule = match:class ^(osu\!)$, rounding 0
windowrule = match:class ^(osu\!)$, no_blur on
windowrule = match:class ^(osu\!)$, no_shadow on
windowrule = match:class ^(osu\!)$, no_anim on
# windowrule = match:class ^(osu!.exe)$, immediate on
# windowrule = match:class ^(osu!)$, stay_focused on
# windowrule = match:class ^(osu!)$, suppress_event activate activatefocus
# windowrule = match:class ^(osu!)$, float on
# windowrule = match:class ^(osu!)$, size 1600 900
# windowrule = match:class ^(osu!)$, center on

# Waydroid: single-window (full-UI) mode
windowrule = match:class ^([Ww]aydroid.*)$, float on
windowrule = match:class ^([Ww]aydroid.*)$, workspace 6
windowrule = match:class ^([Ww]aydroid.*)$, fullscreen on

# osu!stable
windowrule = match:class ^(osu!.exe)$, immediate on

# chrome
windowrule = match:class ^(google-chrome-unstable)$, immediate on

# scrcpy
windowrule = match:class ^(scrcpy)$, float on
windowrule = match:class ^(scrcpy)$, size 416 896
windowrule = match:class ^(scrcpy)$, center on
windowrule = match:class ^(org.kde.plasma-systemmonitor)$, float on
windowrule = match:class ^(org.kde.plasma-systemmonitor)$, size 1304 776
windowrule = match:class ^(org.kde.plasma-systemmonitor)$, center on
windowrule = match:class ^(solaar)$, float on
windowrule = match:class ^(solaar)$, size 951 569
windowrule = match:class ^(solaar)$, center on

# Windscribe
windowrule = match:class ^(Windscribe)$, float on
windowrule = match:class ^(Windscribe)$, center on
windowrule = match:class ^(Windscribe)$, no_anim on

# EasyEffects
# windowrule = match:class ^(com\.github\.wwmm\.easyeffects)$, float on
# windowrule = opacity 0.89 override 0.89 override, match:class .*
