-- DO NOT EDIT THIS FILE. IT IS MANAGED BY THE SHELL AND FOLLOWS STRICT RULES
-- In other words, I ain't writing a lua parser for this, so please be a good boi/girl/whatever
hl.config({render={direct_scanout=2}})
hl.config({render={new_render_scheduling=0}})
hl.config({general={allow_tearing=0}})
