-- Generated from horizontal_signature.conf. Keep the legacy profile as migration provenance.
hl.config({ animations = { enabled = true } })
hl.curve("pop", { type = "bezier", points = {{ 0.26, 1.12 }, { 0.32, 1.0 }} })
hl.curve("glide", { type = "bezier", points = {{ 0.12, 0.92 }, { 0.18, 1.0 }} })
hl.curve("exit", { type = "bezier", points = {{ 0.52, 0.03 }, { 0.72, 0.30 }} })
hl.curve("settle", { type = "bezier", points = {{ 0.20, 1.0 }, { 0.30, 1.0 }} })
hl.curve("liner", { type = "bezier", points = {{ 1, 1 }, { 1, 1 }} })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 3.6, bezier = "pop", style = "popin 78%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2.2, bezier = "exit", style = "popin 88%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 3.2, bezier = "glide", style = "slide" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 3, bezier = "settle" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 2.2, bezier = "settle" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 2.8, bezier = "pop", style = "popin 87%" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 2, bezier = "exit", style = "popin 92%" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 2, bezier = "settle" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.8, bezier = "settle" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5.5, bezier = "glide", style = "slide" })
hl.animation({ leaf = "specialWorkspaceIn", enabled = true, speed = 4, bezier = "glide", style = "slidevert" })
hl.animation({ leaf = "specialWorkspaceOut", enabled = true, speed = 2.6, bezier = "exit", style = "slidevert" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "settle" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 40, bezier = "liner", style = "once" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 3.2, bezier = "settle" })
