# This file is to be overwritten by nwg-displays if you choose to use it.
# nwg-displays is a graphical tool for managing monitors. 
# - Installation for Arch Linux: sudo pacman -S nwg-displays
# - Repo: https://github.com/nwg-piotr/nwg-displays
# Main monitor takes up 1600 logical pixels (1920 / 1.2)
monitor = DP-1, 1920x1080@144, 0x0, 1, vrr, 0

# Arzopa starts immediately after the main monitor
monitor = HDMI-A-1, 1920x1080@144, 1920x540, 1, vrr, 0