-- Generated from horizontal_oneui.conf. Keep the legacy profile as migration provenance.
hl.config({ animations = { enabled = true } })
hl.curve("oneUiPosition", { type = "bezier", points = {{ 0.2, 0.94 }, { 0.05, 1.0 }} })
hl.curve("oneUiAlpha", { type = "bezier", points = {{ 0.0, 1.0 }, { 0.0, 1.0 }} })
hl.curve("oneUiHome", { type = "bezier", points = {{ 0.4, 0.0 }, { 0.0, 1.0 }} })
hl.curve("oneUiAccel", { type = "bezier", points = {{ 0.3, 0 }, { 1, 1 }} })
hl.curve("liner", { type = "bezier", points = {{ 1, 1 }, { 1, 1 }} })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 6.5, bezier = "oneUiPosition", style = "popin 85%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.5, bezier = "oneUiAccel", style = "popin 90%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 5, bezier = "oneUiPosition", style = "slide" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "liner" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 40, bezier = "liner", style = "once" })
hl.animation({ leaf = "fade", enabled = true, speed = 2.5, bezier = "oneUiAlpha" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 2.5, bezier = "oneUiAlpha" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.5, bezier = "oneUiAccel" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "oneUiPosition", style = "popin 88%" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "oneUiAccel", style = "popin 92%" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 4, bezier = "oneUiAlpha" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 4, bezier = "oneUiAlpha" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "oneUiPosition", style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 5, bezier = "oneUiPosition", style = "slidevert" })
