-- Generated from vertical_ios.conf. Keep the legacy profile as migration provenance.
hl.config({ animations = { enabled = true } })
hl.curve("iosDecel", { type = "bezier", points = {{ 0.16, 1 }, { 0.3, 1 }} })
hl.curve("iosStandard", { type = "bezier", points = {{ 0.42, 0 }, { 0.58, 1 }} })
hl.curve("iosSpring", { type = "bezier", points = {{ 0.34, 1.02 }, { 0.4, 1 }} })
hl.curve("liner", { type = "bezier", points = {{ 1, 1 }, { 1, 1 }} })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "iosSpring", style = "popin 92%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "iosStandard", style = "popin 95%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 3, bezier = "iosDecel", style = "slide" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "liner" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 40, bezier = "liner", style = "once" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "iosDecel" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 3, bezier = "iosDecel", style = "popin 95%" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 3, bezier = "iosStandard", style = "popin 96%" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 3, bezier = "iosDecel" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 3, bezier = "iosDecel" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "iosDecel", style = "slidevert" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 4, bezier = "iosDecel", style = "slide" })
